export { Hero } from './Hero'
export { Heading } from './Heading'
export { SubHeading } from './SubHeading'
export { Feature } from './Feature'
export { Button } from './Button'
export { HowItWorks } from './HowItWorks'
export { FeaturesList } from './FeaturesList'
export { NavBar } from './NavBar'
export { Footer } from './Footer'
export { SectionTitle } from './SectionTitle'
export { TestimonialsLogos } from './TestimonialsLogos'
export { LandingProvider } from './LandingProvider'
export { EditableProvider, Editable } from './EditableProvider'
export * from './layout'
